# UI/TownServicesPanel.gd
# Left-side panel showing town services for the current region. Mirrors the
# right-side PartySidePanel: same Tab toggle (synced via PartySidePanel's
# panel_visibility_changed signal), same drag-drop slot style, same value-
# balance trade rule as TradeWindow.
#
# A service NPC appears here when:
#   - the party is in a region whose controlling faction is non-hostile, AND
#   - either the service is legal under that faction's laws OR the player has
#     personally seen the NPC at least once.
#
# Inventory source per service:
#   - Live mode: the NPC is on the current map -> we use its real Inventory.
#   - Snapshot mode: NPC is on a sibling map -> we read/write the persisted
#     Game.npc_state_per_region[region][uid].inventory_items array directly.
extends PanelContainer

const PANEL_WIDTH := 250.0
const SLIDE_DURATION := 0.3
const ITEM_SLOT_SIZE := Vector2(40, 40)
const DUMMY_ICON_PATH := "res://Icons/dummy_icon.png"

# Per-card parchment background. Images are 512x256, generated by
# tools/generate_service_cards.py based on the NPC's primary title id.
const SERVICE_CARDS_DIR := "res://UI/Assets/service_cards/"
const DEFAULT_SERVICE_CARD := "res://UI/Assets/service_cards/default.png"

var game_node: Node = null
var party_panel: Node = null
var panel_visible: bool = true
var _shown_x: float = 0.0
var _hidden_x: float = -PANEL_WIDTH
var _tween: Tween = null

# Per-card UI references; rebuilt on every _repopulate.
var _cards: Array = []  # Array of dictionaries

var scroll: ScrollContainer
var vbox: VBoxContainer
var header_label: Label

# Snapshot of every service NPC's inventory value at the moment the panel
# (re)populates — used to enforce TradeWindow's "NPC must gain >= 0 value"
# rule per individual service. Map: npc_uid -> baseline float.
var _value_baseline: Dictionary = {}

func _ready() -> void:
	mouse_filter = Control.MOUSE_FILTER_STOP
	game_node = get_node_or_null("/root/Game")

	# Panel slides between fully off-screen (-PANEL_WIDTH) and flush-left (0).
	_shown_x = 0.0
	_hidden_x = -PANEL_WIDTH

	# Cosmetic background to match PartySidePanel.
	var bg = StyleBoxFlat.new()
	bg.bg_color = Color(0.10, 0.12, 0.16, 0.92)
	bg.set_corner_radius_all(4)
	bg.set_border_width_all(1)
	bg.border_color = Color(0.6, 0.45, 0.2, 1.0)
	add_theme_stylebox_override("panel", bg)

	var outer = VBoxContainer.new()
	outer.size_flags_vertical = Control.SIZE_EXPAND_FILL
	outer.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	outer.mouse_filter = Control.MOUSE_FILTER_STOP
	add_child(outer)

	header_label = Label.new()
	header_label.text = "Town Services"
	header_label.add_theme_font_size_override("font_size", 13)
	header_label.add_theme_color_override("font_color", Color(0.85, 0.75, 0.4))
	header_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	outer.add_child(header_label)

	scroll = ScrollContainer.new()
	scroll.size_flags_vertical = Control.SIZE_EXPAND_FILL
	scroll.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	scroll.mouse_filter = Control.MOUSE_FILTER_STOP
	outer.add_child(scroll)

	vbox = VBoxContainer.new()
	vbox.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	vbox.mouse_filter = Control.MOUSE_FILTER_STOP
	# Breathing room between adjacent parchment cards so their worn edges
	# don't visually merge.
	vbox.add_theme_constant_override("separation", 6)
	scroll.add_child(vbox)

	# Repopulate on every map load.
	if game_node and game_node.has_signal("map_loaded"):
		game_node.connect("map_loaded", _on_map_loaded)

	# Sync with PartySidePanel's Tab toggle.
	call_deferred("_hook_party_panel_visibility")
	call_deferred("_repopulate")

func _hook_party_panel_visibility() -> void:
	if game_node:
		party_panel = game_node.get_node_or_null("GameUI/PartySidePanel")
	if party_panel and party_panel.has_signal("panel_visibility_changed"):
		party_panel.connect("panel_visibility_changed", _on_party_panel_toggled)
		# Initialise to whatever state the party panel is in.
		_set_panel_open(party_panel.panel_visible, false)

func _on_party_panel_toggled(now_visible: bool) -> void:
	_set_panel_open(now_visible, true)

func _set_panel_open(open: bool, animate: bool) -> void:
	# Panel is anchored to the left edge with both offset_left and offset_right
	# in screen-space. Both must move by the same delta or the panel resizes
	# instead of sliding.
	panel_visible = open
	var target_left: float = 0.0 if open else -PANEL_WIDTH
	var target_right: float = PANEL_WIDTH if open else 0.0
	if not animate:
		offset_left = target_left
		offset_right = target_right
		return
	if _tween and _tween.is_running():
		_tween.kill()
	_tween = create_tween().set_parallel(true)
	_tween.tween_property(self, "offset_left", target_left, SLIDE_DURATION).set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_OUT)
	_tween.tween_property(self, "offset_right", target_right, SLIDE_DURATION).set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_OUT)

func _on_map_loaded(_map_id: String) -> void:
	# Defer one frame so NPCs are fully spawned before we look them up.
	call_deferred("_repopulate")

# ---------------------------------------------------------------------------
# Population
# ---------------------------------------------------------------------------

func _repopulate() -> void:
	for child in vbox.get_children():
		child.queue_free()
	_cards.clear()
	_value_baseline.clear()

	if not game_node:
		visible = false
		return

	var current_map_id: String = str(game_node.get("current_map_id"))
	var region_id: String = RegionDatabase.get_region_for_map(current_map_id)
	if region_id.is_empty():
		visible = false
		return

	var controlling_faction: String = RegionDatabase.get_controlling_faction(region_id)
	if not controlling_faction.is_empty() and FactionDatabase.are_enemies("player", controlling_faction):
		visible = false
		return

	visible = true

	var region_data: Dictionary = RegionDatabase.get_region_data(region_id)
	header_label.text = str(region_data.get("name", region_id)) + " — Services"

	var entries: Array = RegionDatabase.get_service_npcs_in_region(region_id)
	var known: Array = game_node.known_services_per_region.get(region_id, [])

	for entry in entries:
		# A service shows up only when BOTH conditions are met:
		#   1. legal under the controlling faction's laws, AND
		#   2. the player has personally seen the NPC at least once.
		# Either failure hides the entry from the panel.
		var legal: bool = RegionDatabase.is_service_legal(entry["titles"], region_id)
		var seen: bool = entry["npc_uid"] in known
		if not legal or not seen:
			continue
		var card = _build_service_card(entry)
		if card:
			vbox.add_child(card)

func _build_service_card(entry: Dictionary):
	var live_npc = _find_live_npc(entry)
	var inventory_items: Array = _get_service_inventory(entry, live_npc)
	_value_baseline[entry["npc_uid"]] = _compute_inventory_value(inventory_items)

	# Outer wrapper carries the parchment-with-icon background for this service.
	var card_panel = PanelContainer.new()
	card_panel.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	card_panel.mouse_filter = Control.MOUSE_FILTER_STOP
	var card_tex: Texture2D = _get_service_card_texture(entry)
	if card_tex != null:
		var sb := StyleBoxTexture.new()
		sb.texture = card_tex
		# Inset the artwork edges as 9-slice margins so the worn parchment
		# corners don't stretch when the card grows for tall inventories.
		sb.texture_margin_left = 16
		sb.texture_margin_right = 16
		sb.texture_margin_top = 16
		sb.texture_margin_bottom = 16
		# Pad the contents so they don't sit on top of the worn edge.
		sb.set_content_margin_all(8)
		card_panel.add_theme_stylebox_override("panel", sb)

	var container = VBoxContainer.new()
	container.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	container.mouse_filter = Control.MOUSE_FILTER_STOP

	# Header: portrait + title + display_name. gui_input handles left/right click.
	var header = HBoxContainer.new()
	header.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	header.mouse_filter = Control.MOUSE_FILTER_STOP

	var icon = TextureRect.new()
	icon.custom_minimum_size = Vector2(40, 40)
	icon.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	icon.expand_mode = TextureRect.EXPAND_FIT_WIDTH_PROPORTIONAL
	icon.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_load_service_icon(icon, entry)
	header.add_child(icon)

	var name_vbox = VBoxContainer.new()
	name_vbox.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	name_vbox.mouse_filter = Control.MOUSE_FILTER_IGNORE

	# Dark sepia text to read against the parchment background.
	var title_label = Label.new()
	title_label.text = str(entry["titles"][0])
	title_label.add_theme_font_size_override("font_size", 10)
	title_label.add_theme_color_override("font_color", Color(0.45, 0.30, 0.10))
	title_label.mouse_filter = Control.MOUSE_FILTER_IGNORE
	name_vbox.add_child(title_label)

	var name_label = Label.new()
	name_label.text = str(entry["display_name"])
	name_label.add_theme_font_size_override("font_size", 12)
	name_label.add_theme_color_override("font_color", Color(0.15, 0.10, 0.05))
	name_label.mouse_filter = Control.MOUSE_FILTER_IGNORE
	name_vbox.add_child(name_label)

	header.add_child(name_vbox)

	# A small badge showing whether the NPC is on the current map.
	if live_npc == null:
		var away = Label.new()
		away.text = entry["map_id"]
		away.add_theme_font_size_override("font_size", 8)
		away.add_theme_color_override("font_color", Color(0.4, 0.3, 0.2))
		away.mouse_filter = Control.MOUSE_FILTER_IGNORE
		name_vbox.add_child(away)

	container.add_child(header)

	# Inventory grid.
	var inv_grid = GridContainer.new()
	inv_grid.columns = 5
	inv_grid.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	inv_grid.mouse_filter = Control.MOUSE_FILTER_STOP
	container.add_child(inv_grid)

	# Reparent the inner VBox into the textured PanelContainer wrapper.
	card_panel.add_child(container)

	var card_data: Dictionary = {
		"entry": entry,
		"live_npc": live_npc,
		"inv_grid": inv_grid,
		"container": card_panel,  # outer wrapper, used for drop hit-testing
		"header": header,
	}
	_cards.append(card_data)
	header.gui_input.connect(_on_header_input.bind(card_data))
	_refresh_inventory(card_data)

	# When the live NPC's inventory changes (player drops a separate trade
	# elsewhere), refresh this card too.
	if live_npc and live_npc.inventory:
		live_npc.inventory.item_added.connect(_on_live_inventory_changed.bind(card_data))
		live_npc.inventory.item_removed.connect(_on_live_inventory_changed.bind(card_data))

	return card_panel

func _get_service_card_texture(entry: Dictionary) -> Texture2D:
	## Pick the parchment card whose engraved icon matches this NPC's primary
	## title. Falls back to "default.png" if no specific card exists.
	var titles: Array = entry.get("titles", [])
	for title in titles:
		var sid: String = RegionDatabase.title_to_id(str(title))
		var path: String = SERVICE_CARDS_DIR + sid + ".png"
		if ResourceLoader.exists(path):
			return load(path)
	if ResourceLoader.exists(DEFAULT_SERVICE_CARD):
		return load(DEFAULT_SERVICE_CARD)
	return null

func _on_live_inventory_changed(_payload, card_data: Dictionary) -> void:
	_refresh_inventory(card_data)

func _load_service_icon(tex_rect: TextureRect, entry: Dictionary) -> void:
	var icon_path: String = str(entry.get("icon", ""))
	if not icon_path.is_empty() and ResourceLoader.exists(icon_path):
		tex_rect.texture = load(icon_path)
		return
	if ResourceLoader.exists(DUMMY_ICON_PATH):
		tex_rect.texture = load(DUMMY_ICON_PATH)
		return
	var img = Image.create(40, 40, false, Image.FORMAT_RGBA8)
	img.fill(Color(0.5, 0.5, 0.5))
	tex_rect.texture = ImageTexture.create_from_image(img)

# ---------------------------------------------------------------------------
# Inventory accessors (live vs snapshot)
# ---------------------------------------------------------------------------

func _find_live_npc(entry: Dictionary):
	if not game_node:
		return null
	var current_map_id: String = str(game_node.get("current_map_id"))
	if entry.get("map_id", "") != current_map_id:
		return null
	for c in game_node.characters_in_scene:
		if not is_instance_valid(c) or c in game_node.party_chars:
			continue
		if str(c.get_meta("template_id", "")) == entry["template_id"] and \
				str(c.get_meta("unique_name", "")) == entry["unique_name"]:
			return c
	return null

func _get_service_inventory(entry: Dictionary, live_npc) -> Array:
	if live_npc and live_npc.inventory:
		return live_npc.inventory.items
	# Snapshot path
	if not game_node:
		return []
	var region_id: String = RegionDatabase.get_region_for_map(entry["map_id"])
	var bucket: Dictionary = game_node.npc_state_per_region.get(region_id, {})
	var snap: Dictionary = bucket.get(entry["npc_uid"], {})
	return snap.get("inventory_items", [])

func _ensure_snapshot_exists(entry: Dictionary) -> Dictionary:
	## Lazily create a snapshot bucket for an NPC we've never visited yet.
	## Returns a writable snapshot dict.
	var region_id: String = RegionDatabase.get_region_for_map(entry["map_id"])
	if not game_node.npc_state_per_region.has(region_id):
		game_node.npc_state_per_region[region_id] = {}
	var bucket: Dictionary = game_node.npc_state_per_region[region_id]
	if not bucket.has(entry["npc_uid"]):
		bucket[entry["npc_uid"]] = {"inventory_items": []}
	return bucket[entry["npc_uid"]]

# ---------------------------------------------------------------------------
# Inventory rendering
# ---------------------------------------------------------------------------

func _refresh_inventory(card_data: Dictionary) -> void:
	var grid: GridContainer = card_data["inv_grid"]
	for child in grid.get_children():
		child.queue_free()

	var entry: Dictionary = card_data["entry"]
	var live_npc = card_data["live_npc"]
	var items: Array = _get_service_inventory(entry, live_npc)

	# 1) Plain items. Skip ghost dicts that mirror equipped weapons — those are
	#    rendered separately below as WeaponShape entries.
	for i in range(items.size()):
		var item: Dictionary = items[i]
		var equip_slot: String = str(item.get("equip_slot", ""))
		if equip_slot == "Main Hand" or equip_slot == "Off Hand":
			continue
		var raw_stacks = item.get("num_stacks", 1)
		var slot_entry := {
			"kind": "item",
			"display_name": item.get("display_name", item.get("id", "?")),
			"sprite_path": str(item.get("sprite_path", "")) if item.get("sprite_path") != null else "",
			"num_stacks": int(raw_stacks) if raw_stacks != null else 1,
			"equipped": false,
			"hand": "",
			"source_index": i,
			"raw": item,
		}
		grid.add_child(_create_slot(slot_entry, card_data))

	# 2) Weapons. Live NPCs hold WeaponShape nodes in main_hand/off_hand/stowed.
	#    Mirror TradeWindow so service NPCs (e.g. Smith with a rack of weapons)
	#    actually display them.
	if live_npc and live_npc.inventory:
		var inv = live_npc.inventory
		if inv.main_hand_item is WeaponShape:
			grid.add_child(_create_slot(_make_weapon_slot_entry(inv.main_hand_item, "Main", true), card_data))
		if inv.off_hand_item is WeaponShape:
			grid.add_child(_create_slot(_make_weapon_slot_entry(inv.off_hand_item, "Off", true), card_data))
		for w in inv.stowed_items:
			if w is WeaponShape:
				grid.add_child(_create_slot(_make_weapon_slot_entry(w, "", false), card_data))

func _make_weapon_slot_entry(node: WeaponShape, hand: String, equipped: bool) -> Dictionary:
	var sprite_path = node.sprite_path if "sprite_path" in node else ""
	return {
		"kind": "weapon",
		"display_name": node.display_name,
		"sprite_path": str(sprite_path) if sprite_path != null else "",
		"num_stacks": 1,
		"equipped": equipped,
		"hand": hand,
		"source_index": -1,
		"raw": node,
	}

func _create_slot(slot_entry: Dictionary, card_data: Dictionary) -> PanelContainer:
	var slot = PanelContainer.new()
	slot.custom_minimum_size = ITEM_SLOT_SIZE
	slot.mouse_filter = Control.MOUSE_FILTER_STOP
	slot.tooltip_text = "%s (%.0f gold)" % [slot_entry.get("display_name", "?"), _entry_cost(slot_entry)]

	# Subtle dark frame on translucent fill so the parchment shows through
	# but item icons still pop visually.
	var bg = StyleBoxFlat.new()
	bg.bg_color = Color(0.15, 0.10, 0.05, 0.35)
	bg.set_corner_radius_all(4)
	bg.set_border_width_all(1)
	bg.border_color = Color(0.3, 0.2, 0.1, 0.6)
	slot.add_theme_stylebox_override("panel", bg)

	var sprite_path: String = str(slot_entry.get("sprite_path", ""))
	if not sprite_path.is_empty() and ResourceLoader.exists(sprite_path):
		var tex = TextureRect.new()
		tex.texture = load(sprite_path)
		tex.custom_minimum_size = ITEM_SLOT_SIZE
		tex.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
		tex.expand_mode = TextureRect.EXPAND_FIT_WIDTH_PROPORTIONAL
		tex.mouse_filter = Control.MOUSE_FILTER_IGNORE
		slot.add_child(tex)
	else:
		var label = Label.new()
		var disp_name: String = str(slot_entry.get("display_name", "?"))
		label.text = disp_name.substr(0, 4) if disp_name.length() > 4 else disp_name
		label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
		label.add_theme_font_size_override("font_size", 9)
		label.mouse_filter = Control.MOUSE_FILTER_IGNORE
		slot.add_child(label)

	var num_stacks: int = int(slot_entry.get("num_stacks", 1))
	if num_stacks > 1:
		var sl = Label.new()
		sl.text = str(num_stacks)
		sl.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
		sl.vertical_alignment = VERTICAL_ALIGNMENT_BOTTOM
		sl.add_theme_font_size_override("font_size", 10)
		sl.add_theme_color_override("font_color", Color.WHITE)
		sl.add_theme_color_override("font_shadow_color", Color.BLACK)
		sl.add_theme_constant_override("shadow_offset_x", 1)
		sl.add_theme_constant_override("shadow_offset_y", 1)
		sl.custom_minimum_size = ITEM_SLOT_SIZE
		sl.mouse_filter = Control.MOUSE_FILTER_IGNORE
		slot.add_child(sl)

	slot.set_meta("slot_entry", slot_entry)
	slot.set_meta("card_data", card_data)
	return slot

# ---------------------------------------------------------------------------
# Drag/drop
# ---------------------------------------------------------------------------

func _get_drag_data(at_position: Vector2):
	var slot = _find_slot_at(at_position)
	if not slot:
		return null
	var slot_entry: Dictionary = slot.get_meta("slot_entry")
	var card_data: Dictionary = slot.get_meta("card_data")
	set_drag_preview(_create_drag_preview(slot_entry))
	# Mirror TradeWindow's drop dict so PartySidePanel's existing
	# _drop_data already handles us as a "source_npc" path.
	return {
		"source_npc": card_data["live_npc"],  # may be null in snapshot mode
		"snapshot_uid": card_data["entry"]["npc_uid"],
		"snapshot_region": RegionDatabase.get_region_for_map(card_data["entry"]["map_id"]),
		"entry": slot_entry,
		"source_window": self,
	}

func _create_drag_preview(slot_entry: Dictionary) -> Control:
	var sprite_path: String = str(slot_entry.get("sprite_path", ""))
	if not sprite_path.is_empty() and ResourceLoader.exists(sprite_path):
		var tex = TextureRect.new()
		tex.texture = load(sprite_path)
		tex.custom_minimum_size = ITEM_SLOT_SIZE
		tex.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
		tex.expand_mode = TextureRect.EXPAND_FIT_WIDTH_PROPORTIONAL
		return tex
	var label = Label.new()
	label.text = slot_entry.get("display_name", "Item")
	label.add_theme_font_size_override("font_size", 12)
	return label

func _can_drop_data(at_position: Vector2, data) -> bool:
	if data is not Dictionary:
		return false
	if not data.has("source_character"):
		return false
	var card_data = _find_card_at(at_position)
	return not card_data.is_empty()

func _drop_data(at_position: Vector2, data) -> void:
	var card_data = _find_card_at(at_position)
	if card_data.is_empty():
		return
	var source_char = data.get("source_character")
	if not is_instance_valid(source_char):
		return
	var entry: Dictionary = card_data["entry"]
	var slot_entry: Dictionary = data.get("entry", {})

	# We only support items here (weapons could be added later — they need
	# WeaponShape -> data conversion in snapshot mode).
	if slot_entry.get("kind", "") != "item":
		return

	# Pull the item from the party member.
	var item: Dictionary = source_char.inventory.remove_item(slot_entry.get("source_index", -1))
	if item.is_empty():
		return

	# Push into the service NPC. The baseline stays at its original value so
	# the player can withdraw up to what they've given (mirrors TradeWindow's
	# net-non-negative rule, but enforced per-drop instead of at commit time).
	var live_npc = card_data["live_npc"]
	if live_npc and live_npc.inventory:
		live_npc.inventory.add_item(item)
	else:
		var snap: Dictionary = _ensure_snapshot_exists(entry)
		var inv_items: Array = snap.get("inventory_items", [])
		inv_items.append(item)
		snap["inventory_items"] = inv_items

	_refresh_inventory(card_data)
	SfxManager.play_ui("coin_pickup")

# Called from PartySidePanel.gd when the user drags FROM a service slot
# TO a party member. PartySidePanel routes us here for snapshot mode.
func remove_snapshot_item(uid: String, region_id: String, source_index: int) -> Dictionary:
	if not game_node:
		return {}
	var bucket: Dictionary = game_node.npc_state_per_region.get(region_id, {})
	var snap: Dictionary = bucket.get(uid, {})
	var items: Array = snap.get("inventory_items", [])
	if source_index < 0 or source_index >= items.size():
		return {}
	var item: Dictionary = items[source_index].duplicate(true)
	items.remove_at(source_index)
	snap["inventory_items"] = items
	# Refresh any card matching this uid.
	for card in _cards:
		if card["entry"]["npc_uid"] == uid:
			_refresh_inventory(card)
	return item

# Value-balance hook used by PartySidePanel before accepting a snapshot drop.
func can_accept_value_loss(uid: String, item_value: float) -> bool:
	## True if removing `item_value` from the NPC's inventory still leaves
	## them at >= the baseline taken when the panel was last populated.
	for card in _cards:
		if card["entry"]["npc_uid"] == uid:
			var entry: Dictionary = card["entry"]
			var live_npc = card["live_npc"]
			var current: float = _compute_inventory_value(_get_service_inventory(entry, live_npc))
			var baseline: float = float(_value_baseline.get(uid, current))
			return (current - item_value) >= baseline
	return false

func _compute_inventory_value(items: Array) -> float:
	var total: float = 0.0
	for item in items:
		if not (item is Dictionary):
			continue
		var stacks_val = item.get("num_stacks", 1)
		var stacks: int = int(stacks_val) if stacks_val != null else 1
		total += float(item.get("cost", 0.0)) * max(stacks, 1)
	return total

func _entry_cost(slot_entry: Dictionary) -> float:
	## Slot costs differ between item dicts and WeaponShape Nodes.
	if slot_entry.get("kind", "") == "weapon":
		var w = slot_entry.get("raw")
		if w != null and "cost" in w:
			return float(w.cost)
		return 0.0
	var raw = slot_entry.get("raw", {})
	if raw is Dictionary:
		var stacks_val = raw.get("num_stacks", 1)
		var stacks: int = int(stacks_val) if stacks_val != null else 1
		return float(raw.get("cost", 0.0)) * max(stacks, 1)
	return 0.0

# ---------------------------------------------------------------------------
# Click handling on portrait header
# ---------------------------------------------------------------------------

func _on_header_input(event: InputEvent, card_data: Dictionary) -> void:
	if not (event is InputEventMouseButton and event.pressed):
		return
	if event.button_index == MOUSE_BUTTON_RIGHT:
		_show_warp_menu(card_data)
		get_viewport().set_input_as_handled()
	elif event.button_index == MOUSE_BUTTON_LEFT:
		_handle_left_click(card_data)
		get_viewport().set_input_as_handled()

func _show_warp_menu(card_data: Dictionary) -> void:
	var entry: Dictionary = card_data["entry"]
	var menu = PopupMenu.new()
	var map_label: String = str(MapDatabase.get_map_data(entry["map_id"]).get("name", entry["map_id"]))
	menu.add_item("Warp to %s" % map_label, 0)
	if card_data["live_npc"]:
		menu.add_item("Trade", 1)
		if card_data["live_npc"].dialogues.size() > 0:
			menu.add_item("Talk", 2)
	menu.id_pressed.connect(_on_warp_menu_selected.bind(card_data))
	if game_node:
		game_node.context_menu_open = true
	menu.popup_hide.connect(func(): game_node.call_deferred("set", "context_menu_open", false))
	add_child(menu)
	menu.popup(Rect2i(Vector2i(get_global_mouse_position()), Vector2i.ZERO))

func _on_warp_menu_selected(id: int, card_data: Dictionary) -> void:
	SfxManager.play_ui("ui-click")
	var entry: Dictionary = card_data["entry"]
	match id:
		0:
			_warp_to(entry)
		1:
			if card_data["live_npc"]:
				game_node.show_trade_window(card_data["live_npc"])
		2:
			if card_data["live_npc"] and card_data["live_npc"].dialogues.size() > 0:
				DialogueManager.start_dialogue(card_data["live_npc"].dialogues[card_data["live_npc"].current_dialogue_index])

func _handle_left_click(card_data: Dictionary) -> void:
	# Same as right-click "Trade" if NPC is local, else fall back to warp menu.
	var live_npc = card_data["live_npc"]
	if live_npc:
		game_node.show_trade_window(live_npc)
	else:
		_show_warp_menu(card_data)

func _warp_to(entry: Dictionary) -> void:
	if not game_node:
		return
	var target_map: String = entry["map_id"]
	if target_map == game_node.current_map_id:
		return
	var from_map: String = game_node.current_map_id
	game_node.load_map(target_map, from_map)

# ---------------------------------------------------------------------------
# Slot/card lookup
# ---------------------------------------------------------------------------

func _find_slot_at(local_pos: Vector2) -> PanelContainer:
	var global_pos = get_global_transform() * local_pos
	for card in _cards:
		var grid: GridContainer = card["inv_grid"]
		for child in grid.get_children():
			if child is PanelContainer and child.get_global_rect().has_point(global_pos):
				return child
	return null

func _find_card_at(local_pos: Vector2) -> Dictionary:
	var global_pos = get_global_transform() * local_pos
	for card in _cards:
		var c: Control = card["container"]
		if c.get_global_rect().has_point(global_pos):
			return card
	return {}
