"""Make hex-tile icon backgrounds transparent.

The icons generated by tools/generate_icons.py sit on a warm cream parchment
background. To overlay them on arbitrary biome hex tiles in the world map, we
need to strip the parchment.

Approach: floodfill from each of the four image corners using ImageDraw.floodfill
with a colour-distance threshold. Pixels reachable from the corners by a chain of
near-parchment-colour neighbours are tagged as background and made transparent.
This preserves any parchment-coloured DETAILS in the middle of the icon (e.g.
castle walls) because they aren't connected to the edge.

Inputs:  tfa-simultaneous-gemini-1/Assets/HexTiles/icons/<name>.png
Outputs: same path, overwritten in place (originals are saved to <name>_raw.png).

Usage:
    python tools/isolate_icons.py
    python tools/isolate_icons.py --only castle,fort
    python tools/isolate_icons.py --tolerance 30
    python tools/isolate_icons.py --restore         # revert isolated to raw
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

ICONS_DIR = Path("tfa-simultaneous-gemini-1") / "Assets" / "HexTiles" / "icons"
SENTINEL = (255, 0, 255)  # magenta — flagged as background after floodfill


def isolate(img: Image.Image, tolerance: int = 25) -> Image.Image:
    """Return a copy of `img` with the parchment background made transparent."""
    img = img.convert("RGBA")
    w, h = img.size

    # Floodfill on an RGB copy so we can identify edge-connected background.
    rgb = img.convert("RGB").copy()
    for corner in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]:
        ImageDraw.floodfill(rgb, corner, SENTINEL, thresh=tolerance)

    rgb_arr = np.array(rgb)
    is_bg = (
        (rgb_arr[:, :, 0] == SENTINEL[0])
        & (rgb_arr[:, :, 1] == SENTINEL[1])
        & (rgb_arr[:, :, 2] == SENTINEL[2])
    )

    rgba_arr = np.array(img)
    rgba_arr[:, :, 3] = np.where(is_bg, 0, 255).astype(np.uint8)
    return Image.fromarray(rgba_arr, "RGBA")


def process_icon(path: Path, tolerance: int) -> None:
    raw_path = path.with_name(path.stem + "_raw" + path.suffix)
    # Keep an original side-by-side the first time we touch this file.
    if not raw_path.exists():
        shutil.copy2(path, raw_path)
    src = Image.open(raw_path)  # always isolate from the raw, never re-isolate.
    out = isolate(src, tolerance=tolerance)
    out.save(path, "PNG")
    print(f"  isolated {path.name} (raw kept at {raw_path.name})")


def restore_all() -> int:
    """Copy each <name>_raw.png back over <name>.png, if a raw exists."""
    n = 0
    for raw in ICONS_DIR.glob("*_raw.png"):
        target = raw.with_name(raw.name.replace("_raw", ""))
        shutil.copy2(raw, target)
        print(f"  restored {target.name} from {raw.name}")
        n += 1
    return n


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default=None,
                    help="comma-separated icon stems (e.g. castle,fort) to process")
    ap.add_argument("--tolerance", type=int, default=25,
                    help="floodfill colour-distance threshold (default 25). Higher = "
                         "more aggressive background removal.")
    ap.add_argument("--restore", action="store_true",
                    help="revert each <name>.png to its <name>_raw.png copy")
    args = ap.parse_args()

    if args.restore:
        n = restore_all()
        print(f"Restored {n} icons.")
        return 0

    if not ICONS_DIR.exists():
        print(f"ERROR: {ICONS_DIR} does not exist", file=__import__("sys").stderr)
        return 2

    # Find candidate icons (skip *_raw and any non-png).
    all_icons = sorted(p for p in ICONS_DIR.glob("*.png") if not p.stem.endswith("_raw"))
    if args.only:
        wanted = {n.strip() for n in args.only.split(",") if n.strip()}
        all_icons = [p for p in all_icons if p.stem in wanted]
        if not all_icons:
            print(f"ERROR: no matching icons for {wanted}", file=__import__("sys").stderr)
            return 2

    for path in all_icons:
        process_icon(path, args.tolerance)
    print(f"Processed {len(all_icons)} icons (tolerance={args.tolerance}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
